/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClienteTCPTeste.java
 *
 * Created on 23/08/2011, 21:54:59
 */
package socketThreadsAtivosTCP;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.WindowListener;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jjunior
 */
public class ClienteTCPTeste extends javax.swing.JFrame {

    private Integer tentativa;
    private Integer qtdeerro;
    public Boolean DesenhouCabeca;
    public Boolean DesenhouBracodir;
    public Boolean DesenhouBracoesq;
    public Boolean DesenhouPernadir;
    public Boolean DesenhouPernaesq;
    public Boolean Desenhoucorpo;
    public Boolean DesenhouPoste;
    public DefaultTableModel model;
    public Boolean multiplayer;

    /** Creates new form ClienteTCPTeste */
    public ClienteTCPTeste() {
        initComponents();
        //PanelJogoEscolha.setVisible(false);
        // PanelLog.setVisible(false);
        PainelDesenho.setBackground(new Color(240,240,240));
        tentativa = 0;
        qtdeerro = 0;
        this.DesenhouCabeca = false;
        this.DesenhouBracodir = false;
        this.DesenhouBracoesq = false;
        this.DesenhouPernadir = false;
        this.DesenhouPernaesq = false;
        this.Desenhoucorpo = false;
        this.DesenhouPoste = false;
        PanelLog.setVisible(false);
        DesabilitarAlfabeto();
        PanelJogo.setEnabled(false);
        model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Usuario");
        jTable1.setModel(model);
        C1.setForeground(Color.WHITE);
        C2.setForeground(Color.WHITE);
        C3.setForeground(Color.WHITE);
        C4.setForeground(Color.WHITE);
        C5.setForeground(Color.WHITE);
        C6.setForeground(Color.WHITE);
        C7.setForeground(Color.WHITE);
        C8.setForeground(Color.WHITE);
        C9.setForeground(Color.WHITE);
        C10.setForeground(Color.WHITE);
        C1.setBackground(Color.WHITE);
        C2.setBackground(Color.WHITE);
        C3.setBackground(Color.WHITE);
        C4.setBackground(Color.WHITE);
        C5.setBackground(Color.WHITE);
        C6.setBackground(Color.WHITE);
        C7.setBackground(Color.WHITE);
        C8.setBackground(Color.WHITE);
        C9.setBackground(Color.WHITE);
        C10.setBackground(Color.WHITE);



    }

    public void AddNoModel(String[] valor) {
        model.addRow(valor);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLog = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Panelconexao = new javax.swing.JPanel();
        BtnConectar = new javax.swing.JButton();
        CTPorta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CTLocalhost = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CTId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BtnDesconecta = new javax.swing.JButton();
        PanelJogoEscolha = new javax.swing.JPanel();
        BtnMulti = new javax.swing.JButton();
        BtnSingle = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnCriarnovo = new javax.swing.JButton();
        BtnEntrar = new javax.swing.JButton();
        BtnAtualizar = new javax.swing.JButton();
        PanelJogo = new javax.swing.JPanel();
        PainelDesenho = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        E = new javax.swing.JButton();
        A = new javax.swing.JButton();
        B = new javax.swing.JButton();
        C = new javax.swing.JButton();
        D = new javax.swing.JButton();
        F = new javax.swing.JButton();
        G = new javax.swing.JButton();
        H = new javax.swing.JButton();
        I = new javax.swing.JButton();
        J = new javax.swing.JButton();
        L = new javax.swing.JButton();
        O = new javax.swing.JButton();
        N = new javax.swing.JButton();
        M = new javax.swing.JButton();
        K = new javax.swing.JButton();
        R = new javax.swing.JButton();
        Q = new javax.swing.JButton();
        S = new javax.swing.JButton();
        T = new javax.swing.JButton();
        P = new javax.swing.JButton();
        Z = new javax.swing.JButton();
        X = new javax.swing.JButton();
        V = new javax.swing.JButton();
        U = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        W = new javax.swing.JButton();
        Y = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        CTDica = new javax.swing.JTextArea();
        BtnenviarPalavra = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        C1 = new javax.swing.JTextField();
        C2 = new javax.swing.JTextField();
        C3 = new javax.swing.JTextField();
        C4 = new javax.swing.JTextField();
        C5 = new javax.swing.JTextField();
        C6 = new javax.swing.JTextField();
        C8 = new javax.swing.JTextField();
        C7 = new javax.swing.JTextField();
        C9 = new javax.swing.JTextField();
        C10 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Jpalavra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        LabelPlayerII = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LabelPlayerI = new javax.swing.JLabel();
        PONTOSPLAYII = new javax.swing.JTextField();
        PONTOSPLAYI = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo Da Forca - Versão 0.00000000001");
        setMinimumSize(new java.awt.Dimension(967, 639));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLog.setBackground(new java.awt.Color(204, 255, 204));
        PanelLog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        PanelLog.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, 155, 105));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        PanelLog.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 17, 155, 49));

        jButton3.setText("Enviar");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PanelLog.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 220, 83, -1));

        jLabel3.setText("Mensagem:");
        PanelLog.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel4.setText("Resposta:");
        PanelLog.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, -1, -1));

        getContentPane().add(PanelLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 209, 156, 419));

        Panelconexao.setBackground(new java.awt.Color(102, 255, 153));
        Panelconexao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnConectar.setText("Conectar");
        BtnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConectarActionPerformed(evt);
            }
        });
        Panelconexao.add(BtnConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 46, -1, 30));

        CTPorta.setText("6789");
        Panelconexao.add(CTPorta, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 20, 40, -1));

        jLabel2.setText("Porta:");
        Panelconexao.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 0, -1, -1));

        CTLocalhost.setText("localhost");
        Panelconexao.add(CTLocalhost, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 20, 68, -1));

        jLabel1.setText("Server:");
        Panelconexao.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 0, -1, -1));

        CTId.setEditable(false);
        Panelconexao.add(CTId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 38, -1));

        jLabel5.setText("ID:");
        Panelconexao.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 0, -1, -1));

        BtnDesconecta.setText("Desconectar");
        BtnDesconecta.setEnabled(false);
        BtnDesconecta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDesconectaActionPerformed(evt);
            }
        });
        Panelconexao.add(BtnDesconecta, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 47, 101, 29));

        getContentPane().add(Panelconexao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 255, 110));

        PanelJogoEscolha.setBackground(new java.awt.Color(204, 255, 153));
        PanelJogoEscolha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnMulti.setText("Multiplayer");
        BtnMulti.setEnabled(false);
        BtnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultiActionPerformed(evt);
            }
        });
        PanelJogoEscolha.add(BtnMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 120, 40));

        BtnSingle.setText("Singleplayer");
        BtnSingle.setEnabled(false);
        BtnSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSingleActionPerformed(evt);
            }
        });
        PanelJogoEscolha.add(BtnSingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        PanelJogoEscolha.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 230, 360));

        BtnCriarnovo.setText("Criar Novo");
        BtnCriarnovo.setEnabled(false);
        BtnCriarnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCriarnovoActionPerformed(evt);
            }
        });
        PanelJogoEscolha.add(BtnCriarnovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 40));

        BtnEntrar.setText("Entrar");
        BtnEntrar.setEnabled(false);
        BtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrarActionPerformed(evt);
            }
        });
        PanelJogoEscolha.add(BtnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 120, 40));

        BtnAtualizar.setText("Atualizar");
        BtnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtualizarActionPerformed(evt);
            }
        });
        PanelJogoEscolha.add(BtnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));

        getContentPane().add(PanelJogoEscolha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, 255, 510));

        PanelJogo.setBackground(new java.awt.Color(204, 204, 255));
        PanelJogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelDesenho.setLayout(new java.awt.BorderLayout());
        PanelJogo.add(PainelDesenho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 250));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        E.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        E.setText("E");
        E.setPreferredSize(new java.awt.Dimension(43, 23));
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });
        jPanel2.add(E, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        A.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        A.setText("A");
        A.setPreferredSize(new java.awt.Dimension(43, 23));
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });
        jPanel2.add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        B.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        B.setText("B");
        B.setPreferredSize(new java.awt.Dimension(43, 23));
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        jPanel2.add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        C.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        C.setText("C");
        C.setPreferredSize(new java.awt.Dimension(43, 23));
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });
        jPanel2.add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        D.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        D.setText("D");
        D.setPreferredSize(new java.awt.Dimension(43, 23));
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });
        jPanel2.add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        F.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        F.setText("F");
        F.setPreferredSize(new java.awt.Dimension(43, 23));
        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FActionPerformed(evt);
            }
        });
        jPanel2.add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        G.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        G.setText("G");
        G.setPreferredSize(new java.awt.Dimension(43, 23));
        G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GActionPerformed(evt);
            }
        });
        jPanel2.add(G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        H.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        H.setText("H");
        H.setPreferredSize(new java.awt.Dimension(43, 23));
        H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HActionPerformed(evt);
            }
        });
        jPanel2.add(H, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        I.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        I.setText("I");
        I.setPreferredSize(new java.awt.Dimension(43, 23));
        I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IActionPerformed(evt);
            }
        });
        jPanel2.add(I, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        J.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        J.setText("J");
        J.setPreferredSize(new java.awt.Dimension(43, 23));
        J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JActionPerformed(evt);
            }
        });
        jPanel2.add(J, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        L.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        L.setText("L");
        L.setPreferredSize(new java.awt.Dimension(43, 23));
        L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LActionPerformed(evt);
            }
        });
        jPanel2.add(L, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        O.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        O.setText("O");
        O.setPreferredSize(new java.awt.Dimension(43, 23));
        O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OActionPerformed(evt);
            }
        });
        jPanel2.add(O, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        N.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        N.setText("N");
        N.setPreferredSize(new java.awt.Dimension(43, 23));
        N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NActionPerformed(evt);
            }
        });
        jPanel2.add(N, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        M.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        M.setText("M");
        M.setPreferredSize(new java.awt.Dimension(43, 23));
        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });
        jPanel2.add(M, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        K.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        K.setText("K");
        K.setPreferredSize(new java.awt.Dimension(43, 23));
        K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KActionPerformed(evt);
            }
        });
        jPanel2.add(K, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        R.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        R.setText("R");
        R.setPreferredSize(new java.awt.Dimension(43, 23));
        R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RActionPerformed(evt);
            }
        });
        jPanel2.add(R, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        Q.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Q.setText("Q");
        Q.setPreferredSize(new java.awt.Dimension(43, 23));
        Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QActionPerformed(evt);
            }
        });
        jPanel2.add(Q, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        S.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        S.setText("S");
        S.setPreferredSize(new java.awt.Dimension(43, 23));
        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SActionPerformed(evt);
            }
        });
        jPanel2.add(S, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        T.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        T.setText("T");
        T.setPreferredSize(new java.awt.Dimension(43, 23));
        T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TActionPerformed(evt);
            }
        });
        jPanel2.add(T, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        P.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        P.setText("P");
        P.setPreferredSize(new java.awt.Dimension(43, 23));
        P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PActionPerformed(evt);
            }
        });
        jPanel2.add(P, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        Z.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Z.setText("Z");
        Z.setPreferredSize(new java.awt.Dimension(43, 23));
        Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZActionPerformed(evt);
            }
        });
        jPanel2.add(Z, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        X.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        X.setText("X");
        X.setPreferredSize(new java.awt.Dimension(43, 23));
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });
        jPanel2.add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        V.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        V.setText("V");
        V.setPreferredSize(new java.awt.Dimension(43, 23));
        V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VActionPerformed(evt);
            }
        });
        jPanel2.add(V, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        U.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        U.setText("U");
        U.setPreferredSize(new java.awt.Dimension(43, 23));
        U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UActionPerformed(evt);
            }
        });
        jPanel2.add(U, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        jButton27.setText("Y");
        jPanel2.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        W.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        W.setText("W");
        W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WActionPerformed(evt);
            }
        });
        jPanel2.add(W, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        Y.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Y.setText("Y");
        Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YActionPerformed(evt);
            }
        });
        jPanel2.add(Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        PanelJogo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 420, 130));

        CTDica.setColumns(20);
        CTDica.setRows(5);
        CTDica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CTDicaKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(CTDica);

        PanelJogo.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 350, 40));

        BtnenviarPalavra.setText("Enviar Palavra");
        BtnenviarPalavra.setEnabled(false);
        BtnenviarPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnenviarPalavraActionPerformed(evt);
            }
        });
        PanelJogo.add(BtnenviarPalavra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, -1, -1));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        C1.setEditable(false);
        C1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        C1.setForeground(new java.awt.Color(255, 255, 255));
        C1.setText("A");
        C1.setAutoscrolls(false);
        C1.setMaximumSize(new java.awt.Dimension(31, 35));
        C1.setMinimumSize(new java.awt.Dimension(31, 35));
        C1.setPreferredSize(new java.awt.Dimension(31, 35));
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        jPanel3.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        C2.setEditable(false);
        C2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        C2.setForeground(new java.awt.Color(255, 255, 255));
        C2.setText("W");
        C2.setAutoscrolls(false);
        C2.setMaximumSize(new java.awt.Dimension(31, 35));
        C2.setMinimumSize(new java.awt.Dimension(31, 35));
        C2.setPreferredSize(new java.awt.Dimension(31, 35));
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });
        jPanel3.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 11, -1, -1));

        C3.setEditable(false);
        C3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        C3.setForeground(new java.awt.Color(255, 255, 255));
        C3.setText("W");
        C3.setAutoscrolls(false);
        C3.setMaximumSize(new java.awt.Dimension(31, 35));
        C3.setMinimumSize(new java.awt.Dimension(31, 35));
        C3.setPreferredSize(new java.awt.Dimension(31, 35));
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });
        jPanel3.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 11, -1, -1));

        C4.setEditable(false);
        C4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        C4.setForeground(new java.awt.Color(255, 255, 255));
        C4.setText("W");
        C4.setAutoscrolls(false);
        C4.setMaximumSize(new java.awt.Dimension(31, 35));
        C4.setMinimumSize(new java.awt.Dimension(31, 35));
        C4.setPreferredSize(new java.awt.Dimension(31, 35));
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });
        jPanel3.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 11, -1, -1));

        C5.setEditable(false);
        C5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        C5.setForeground(new java.awt.Color(255, 255, 255));
        C5.setText("W");
        C5.setAutoscrolls(false);
        C5.setMaximumSize(new java.awt.Dimension(31, 35));
        C5.setMinimumSize(new java.awt.Dimension(31, 35));
        C5.setPreferredSize(new java.awt.Dimension(31, 35));
        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5ActionPerformed(evt);
            }
        });
        jPanel3.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 11, -1, -1));

        C6.setEditable(false);
        C6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        C6.setForeground(new java.awt.Color(255, 255, 255));
        C6.setText("W");
        C6.setAutoscrolls(false);
        C6.setMaximumSize(new java.awt.Dimension(31, 35));
        C6.setMinimumSize(new java.awt.Dimension(31, 35));
        C6.setPreferredSize(new java.awt.Dimension(31, 35));
        C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C6ActionPerformed(evt);
            }
        });
        jPanel3.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 11, -1, -1));

        C8.setEditable(false);
        C8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        C8.setForeground(new java.awt.Color(255, 255, 255));
        C8.setText("W");
        C8.setAutoscrolls(false);
        C8.setMaximumSize(new java.awt.Dimension(31, 35));
        C8.setMinimumSize(new java.awt.Dimension(31, 35));
        C8.setPreferredSize(new java.awt.Dimension(31, 35));
        C8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C8ActionPerformed(evt);
            }
        });
        jPanel3.add(C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 11, -1, -1));

        C7.setEditable(false);
        C7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        C7.setForeground(new java.awt.Color(255, 255, 255));
        C7.setText("W");
        C7.setAutoscrolls(false);
        C7.setMaximumSize(new java.awt.Dimension(31, 35));
        C7.setMinimumSize(new java.awt.Dimension(31, 35));
        C7.setPreferredSize(new java.awt.Dimension(31, 35));
        C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C7ActionPerformed(evt);
            }
        });
        jPanel3.add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 11, -1, -1));

        C9.setEditable(false);
        C9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        C9.setForeground(new java.awt.Color(255, 255, 255));
        C9.setAutoscrolls(false);
        C9.setMaximumSize(new java.awt.Dimension(31, 35));
        C9.setMinimumSize(new java.awt.Dimension(31, 35));
        C9.setPreferredSize(new java.awt.Dimension(31, 35));
        C9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C9ActionPerformed(evt);
            }
        });
        jPanel3.add(C9, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 11, -1, -1));

        C10.setEditable(false);
        C10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        C10.setForeground(new java.awt.Color(255, 255, 255));
        C10.setAutoscrolls(false);
        C10.setMaximumSize(new java.awt.Dimension(31, 35));
        C10.setMinimumSize(new java.awt.Dimension(31, 35));
        C10.setPreferredSize(new java.awt.Dimension(31, 35));
        C10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C10ActionPerformed(evt);
            }
        });
        jPanel3.add(C10, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 11, -1, -1));

        PanelJogo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 380, 60));

        jLabel6.setText("Palavra");
        PanelJogo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 530, 40, 20));

        Jpalavra.setEnabled(false);
        Jpalavra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JpalavraKeyPressed(evt);
            }
        });
        PanelJogo.add(Jpalavra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 190, -1));

        jLabel9.setText("Dica:");
        PanelJogo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        getContentPane().add(PanelJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 11, 451, 617));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 24, 0, 0));

        jPanel5.setBackground(new java.awt.Color(255, 204, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelPlayerII.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        LabelPlayerII.setText("PLAYER II");
        jPanel5.add(LabelPlayerII, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setText("PONTUAÇÀO");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        LabelPlayerI.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        LabelPlayerI.setText("PLAYER I");
        jPanel5.add(LabelPlayerI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPanel5.add(PONTOSPLAYII, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, -1));
        jPanel5.add(PONTOSPLAYI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 11, 156, 192));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConectarActionPerformed
        try {
            String server = CTLocalhost.getText();
            int porta = Integer.parseInt(CTPorta.getText());
            tcpClient = new TCPClient(server, porta, this);
            BtnConectar.setEnabled(false);
            BtnDesconecta.setEnabled(true);
            BtnMulti.setEnabled(true);
            BtnSingle.setEnabled(true);
            BtnCriarnovo.setEnabled(false);
            BtnEntrar.setEnabled(false);


            // jButton3.setEnabled(true);            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnConectarActionPerformed

    public void CarregaVazioNoCT() {
        Desenho desss = new Desenho();
        desss.redesenhaCinza(PainelDesenho.getGraphics());
        
        qtdeerro = 0;
        tentativa = 0;
        C1.setText(null);
        C2.setText(null);
        C3.setText(null);
        C4.setText(null);
        C5.setText(null);
        C6.setText(null);
        C7.setText(null);
        C8.setText(null);
        C9.setText(null);
        C10.setText(null);
        C1.setVisible(false);
        C2.setVisible(false);
        C3.setVisible(false);
        C4.setVisible(false);
        C5.setVisible(false);
        C6.setVisible(false);
        C7.setVisible(false);
        C8.setVisible(false);
        C9.setVisible(false);
        C10.setVisible(false);
        C1.setForeground(Color.WHITE);
        C2.setForeground(Color.WHITE);
        C3.setForeground(Color.WHITE);
        C4.setForeground(Color.WHITE);
        C5.setForeground(Color.WHITE);
        C6.setForeground(Color.WHITE);
        C7.setForeground(Color.WHITE);
        C8.setForeground(Color.WHITE);
        C9.setForeground(Color.WHITE);
        C10.setForeground(Color.WHITE);
        A.setEnabled(true);
        B.setEnabled(true);
        C.setEnabled(true);
        D.setEnabled(true);
        E.setEnabled(true);
        F.setEnabled(true);
        G.setEnabled(true);
        H.setEnabled(true);
        I.setEnabled(true);
        J.setEnabled(true);
        K.setEnabled(true);
        L.setEnabled(true);
        M.setEnabled(true);
        N.setEnabled(true);
        O.setEnabled(true);
        P.setEnabled(true);
        Q.setEnabled(true);
        R.setEnabled(true);
        S.setEnabled(true);
        T.setEnabled(true);
        U.setEnabled(true);
        V.setEnabled(true);
        X.setEnabled(true);
        Z.setEnabled(true);
        W.setEnabled(true);
        Y.setEnabled(true);
        this.DesenhouCabeca = false;
        this.DesenhouBracodir = false;
        this.DesenhouBracoesq = false;
        this.DesenhouPernadir = false;
        this.DesenhouPernaesq = false;
        this.Desenhoucorpo = false;
        this.DesenhouPoste = true;
        //PainelDesenho.repaint();
        DesenharnoPainel();




    }

    public void AlteraPlacarPlayerI(String pontos) {
        PONTOSPLAYI.setText(pontos);
        //System.out.println(pontos + "  Pontos");

    }

    public void AlteraPlacarPlayerII(String pontos) {
        PONTOSPLAYII.setText(pontos);
        //System.out.println(pontos + "  Pontos");

    }

    public void CarregaUsuar(String usuario) {
        CTId.setText(usuario);

    }

    public void DesabilitarAlfabeto() {
        A.setEnabled(false);
        B.setEnabled(false);
        C.setEnabled(false);
        D.setEnabled(false);
        E.setEnabled(false);
        F.setEnabled(false);
        G.setEnabled(false);
        H.setEnabled(false);
        I.setEnabled(false);
        J.setEnabled(false);
        K.setEnabled(false);
        L.setEnabled(false);
        M.setEnabled(false);
        N.setEnabled(false);
        O.setEnabled(false);
        P.setEnabled(false);
        Q.setEnabled(false);
        R.setEnabled(false);
        S.setEnabled(false);
        T.setEnabled(false);
        U.setEnabled(false);
        V.setEnabled(false);
        X.setEnabled(false);
        Z.setEnabled(false);
        W.setEnabled(false);
        Y.setEnabled(false);
    }

    public void CarregaPalavra(String palavra, String Dica) {
        char[] p = palavra.toUpperCase().toCharArray();
        CarregaVazioNoCT();
        CTDica.setText(Dica);
        Desenho des = new Desenho();
        //des.poste(PainelDesenho.getGraphics());
        //this.DesenhouPoste = true;
        //DesenharnoPainel();
        for (int i = 0; i < palavra.length(); i++) {
            switch (i) {
                case 0:
                    C1.setText(String.valueOf(p[i]));
                    C1.setVisible(true);
                    break;
                case 1:
                    C2.setText(String.valueOf(p[i]));
                    C2.setVisible(true);
                    break;
                case 2:
                    C3.setText(String.valueOf(p[i]));
                    C3.setVisible(true);
                    break;
                case 3:
                    C4.setText(String.valueOf(p[i]));
                    C4.setVisible(true);
                    break;
                case 4:
                    C5.setText(String.valueOf(p[i]));
                    C5.setVisible(true);
                    break;
                case 5:
                    C6.setText(String.valueOf(p[i]));
                    C6.setVisible(true);
                    break;
                case 6:
                    C7.setText(String.valueOf(p[i]));
                    C7.setVisible(true);
                    break;
                case 7:
                    C8.setText(String.valueOf(p[i]));
                    C8.setVisible(true);
                    break;
                case 8:
                    C9.setText(String.valueOf(p[i]));
                    C9.setVisible(true);
                    break;
                case 9:
                    C10.setText(String.valueOf(p[i]));
                    C10.setVisible(true);
                    break;
            }

        }


    }

    public void desconect() {
        this.BtnDesconectaActionPerformed(null);
    }

    private void BtnDesconectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDesconectaActionPerformed

        try {
            this.tcpClient.writeMessage(CTId.getText() + "|SAIU");
            this.tcpClient.closeConnection();


        } catch (IOException ex) {
            // JOptionPane.showMessageDialog(this,
            //       ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }

        BtnConectar.setEnabled(true);
        BtnDesconecta.setEnabled(false);
        jButton3.setEnabled(false);
        BtnMulti.setEnabled(false);
        BtnSingle.setEnabled(false);
        //PanelJogoEscolha.setVisible(false);
        BtnCriarnovo.setEnabled(false);
        BtnEntrar.setEnabled(false);
        jTable1.setEnabled(false);
        // PanelLog.setVisible(false);
        CTId.setText("");
        jTextArea1.setText("");
        jTextArea2.setText("");
        PONTOSPLAYII.setText("0");
        PONTOSPLAYII.setText("0");
        CarregaVazioNoCT();
        DesabilitarAlfabeto();
        Jpalavra.setText("");
        CTDica.setText("");
        this.DesenhouCabeca = false;
        this.DesenhouBracodir = false;
        this.DesenhouBracoesq = false;
        this.DesenhouPernadir = false;
        this.DesenhouPernaesq = false;
        this.Desenhoucorpo = false;
        this.DesenhouPoste = false;
        this.limpaJtable();
        DesenharnoPainel();
        //PainelDesenho.repaint();

    }//GEN-LAST:event_BtnDesconectaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.tcpClient.writeMessage(CTId.getText() + "|msg|" + jTextArea1.getText() + "|0");

    }//GEN-LAST:event_jButton3ActionPerformed

private void BtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultiActionPerformed
// TODO add your handling code here:
    this.multiplayer = true;
    BtnSingle.setEnabled(false);
    BtnCriarnovo.setEnabled(true);
    BtnenviarPalavra.setEnabled(false);
    BtnenviarPalavra.setVisible(true);
    LabelPlayerII.setVisible(true);
    PONTOSPLAYII.setVisible(true);
    PONTOSPLAYI.setText("0");
    PONTOSPLAYII.setText("0");
    //BtnEntrar.setEnabled(true);
    jTable1.setEnabled(true);
    this.tcpClient.writeMessage(CTId.getText() + "|tipo|2|CARREGAR");

}//GEN-LAST:event_BtnMultiActionPerformed

private void BtnSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSingleActionPerformed
// TODO add your handling code here:
    this.multiplayer = false;
    this.tcpClient.writeMessage(CTId.getText() + "|tipo|1|0");
    BtnSingle.setEnabled(false);
    BtnenviarPalavra.setVisible(false);
    BtnMulti.setEnabled(false);
    LabelPlayerII.setVisible(false);
    PONTOSPLAYII.setVisible(false);
    PONTOSPLAYI.setText("0");
    PanelJogo.setEnabled(true);
    DesenharnoPainel();


}//GEN-LAST:event_BtnSingleActionPerformed

private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_C1ActionPerformed

private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_C2ActionPerformed

private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_C3ActionPerformed

private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_C4ActionPerformed

private void C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_C5ActionPerformed

private void C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C6ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_C6ActionPerformed

private void C8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C8ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_C8ActionPerformed

private void C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C7ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_C7ActionPerformed

private void C9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C9ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_C9ActionPerformed

private void C10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C10ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_C10ActionPerformed

private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(A.getText().toUpperCase());
    A.setEnabled(false);
}//GEN-LAST:event_AActionPerformed

private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(B.getText());
    B.setEnabled(false);
}//GEN-LAST:event_BActionPerformed

private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(C.getText());
    C.setEnabled(false);
}//GEN-LAST:event_CActionPerformed

private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(D.getText());
    D.setEnabled(false);
}//GEN-LAST:event_DActionPerformed

private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(E.getText());
    E.setEnabled(false);
}//GEN-LAST:event_EActionPerformed

private void FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(F.getText());
    F.setEnabled(false);
}//GEN-LAST:event_FActionPerformed

private void GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(G.getText());
    G.setEnabled(false);
}//GEN-LAST:event_GActionPerformed

private void HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(H.getText());
    H.setEnabled(false);
}//GEN-LAST:event_HActionPerformed

private void IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(I.getText());
    I.setEnabled(false);
}//GEN-LAST:event_IActionPerformed

private void JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(J.getText());
    J.setEnabled(false);
}//GEN-LAST:event_JActionPerformed

private void KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(K.getText());
    K.setEnabled(false);
}//GEN-LAST:event_KActionPerformed

private void LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(L.getText());
    L.setEnabled(false);
}//GEN-LAST:event_LActionPerformed

private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(M.getText());
    M.setEnabled(false);
}//GEN-LAST:event_MActionPerformed

private void NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(N.getText());
    N.setEnabled(false);
}//GEN-LAST:event_NActionPerformed

private void OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(O.getText());
    O.setEnabled(false);
}//GEN-LAST:event_OActionPerformed

private void PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(P.getText());
    P.setEnabled(false);
}//GEN-LAST:event_PActionPerformed

private void QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(Q.getText());
    Q.setEnabled(false);
}//GEN-LAST:event_QActionPerformed

private void RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(R.getText());
    R.setEnabled(false);
}//GEN-LAST:event_RActionPerformed

private void SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(S.getText());
    S.setEnabled(false);
}//GEN-LAST:event_SActionPerformed

private void TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(T.getText());
    T.setEnabled(false);
}//GEN-LAST:event_TActionPerformed

private void UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(U.getText());
    U.setEnabled(false);
}//GEN-LAST:event_UActionPerformed

private void VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(V.getText());
    V.setEnabled(false);
}//GEN-LAST:event_VActionPerformed

private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(X.getText());
    X.setEnabled(false);
}//GEN-LAST:event_XActionPerformed

private void ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(Z.getText());
    Z.setEnabled(false);
}//GEN-LAST:event_ZActionPerformed

    public void HabilitaPalavra() {
        JOptionPane.showMessageDialog(rootPane, "Digite A Dica e A Palavra!");
        CarregaVazioNoCT();        
        DesabilitarAlfabeto();
        Jpalavra.setEnabled(true);
        CTDica.setEditable(true);
        BtnenviarPalavra.setEnabled(true);
        Jpalavra.setText("");
        CTDica.setText("");
        DesenharnoPainel();
    }

private void BtnenviarPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnenviarPalavraActionPerformed
// TODO add your handling code here:
    Verificacao pa = new Verificacao();
    if (!pa.VerificaPalavra(Jpalavra.getText().toUpperCase()) || Jpalavra.getText() == null) {
        JOptionPane.showMessageDialog(rootPane, "Palavra nÃ£o pode haver caracteres especiais, e nem acentos. apenas letras \n Tamanho 1 ~ 10");
    } else if(!pa.VerificaDica(CTDica.getText().toUpperCase()) || CTDica.getText() == null)  {
        JOptionPane.showMessageDialog(rootPane, "Dica nÃ£o pode haver | (pipe) \n tamanho 1 ~ 100");
    } else {    // CarregaPalavra("davi", "teste");
        this.tcpClient.writeMessage(CTId.getText() + "|tipo|2|PALAVRAENVIADA|" + Jpalavra.getText().toUpperCase() + "|" + CTDica.getText().toUpperCase());
        BtnenviarPalavra.setEnabled(false);
        CTDica.setEditable(false);
        Jpalavra.setEnabled(false);
        Jpalavra.setText("");
        CTDica.setText("Palavra Enviada... Aguarde  o jogador finalizar o turno, e logo voce irÃ¡ jogar.");
    }
}//GEN-LAST:event_BtnenviarPalavraActionPerformed

private void WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(W.getText());
    W.setEnabled(false);
}//GEN-LAST:event_WActionPerformed

private void YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YActionPerformed
// TODO add your handling code here:
    VerificaSeExisteLetra(Y.getText());
    Y.setEnabled(false);
}//GEN-LAST:event_YActionPerformed

private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
// TODO add your handling code here:
    try {
        this.tcpClient.closeConnection();

    } catch (IOException ex) {
    }
}//GEN-LAST:event_formWindowClosed

    @Override
    public void dispose() {
        super.dispose();
    }

    @Override
    protected void finalize() throws Throwable {
        try {
            this.tcpClient.closeConnection();
        } catch (IOException ex) {
        }
        super.finalize();
    }

private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
// TODO add your handling code here:
}//GEN-LAST:event_formWindowDeactivated

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    if (BtnDesconecta.isEnabled()) {
        BtnDesconectaActionPerformed(null);
        try {
            // TODO add your handling code here:
            this.tcpClient.closeConnection();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
}//GEN-LAST:event_formWindowClosing

private void BtnCriarnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCriarnovoActionPerformed
// TODO add your handling code here:
    this.tcpClient.writeMessage(CTId.getText() + "|tipo|2|CRIAR");
    LabelPlayerI.setText("Player I  - VOCÃŠ");
    LabelPlayerII.setText("Player II");

}//GEN-LAST:event_BtnCriarnovoActionPerformed
    public void limpaJtable() {
        int k = model.getRowCount();

        if (k > 0) {
            for (int i = 0; i <= k; i++) {
                model.removeRow(0);
            }
        }
    }

private void BtnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtualizarActionPerformed
// TODO add your handling code here:
    limpaJtable();
    this.tcpClient.writeMessage(CTId.getText() + "|tipo|2|CARREGAR");
}//GEN-LAST:event_BtnAtualizarActionPerformed

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
// TODO add your handling code here:
    BtnEntrar.setEnabled(true);

}//GEN-LAST:event_jTable1MouseClicked

private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed
// TODO add your handling code here:
    String id = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
    this.tcpClient.writeMessage(CTId.getText() + "|tipo|2|ENTRAR|" + id);
    LabelPlayerII.setText("Player II  - VOCÃŠ");
    LabelPlayerI.setText("Player I");


}//GEN-LAST:event_BtnEntrarActionPerformed

private void JpalavraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JpalavraKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_JpalavraKeyPressed

private void CTDicaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CTDicaKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_CTDicaKeyPressed

private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
// TODO add your handling code here:
    BtnEntrar.setEnabled(true);
}//GEN-LAST:event_jTable1MousePressed

private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
// TODO add your handling code here:
    BtnEntrar.setEnabled(true);
}//GEN-LAST:event_jTable1MouseReleased
    public void CarregaCTDICA(String txt) {
        CTDica.setText(txt);

    }

    public void OptionPaneShow(String txt) {
        JOptionPane.showMessageDialog(rootPane, txt);

    }

    public void DesabilitaBTn() {
        BtnCriarnovo.setEnabled(false);
        BtnEntrar.setEnabled(false);
        BtnMulti.setEnabled(false);
    }

    public void escreverMensagem(String message) {
        String msg[] = message.split("\\|");
        CTId.setText(msg[0]);
        if (msg[1].equals("pronto")) {
            jButton3.setEnabled(true);
            jTextArea2.append(msg[2] + "\n");
        }
        if (msg[1].equals("msg")) {
            jTextArea2.append(msg[2] + "\n");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ClienteTCPTeste().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JButton B;
    private javax.swing.JButton BtnAtualizar;
    private javax.swing.JButton BtnConectar;
    private javax.swing.JButton BtnCriarnovo;
    private javax.swing.JButton BtnDesconecta;
    private javax.swing.JButton BtnEntrar;
    private javax.swing.JButton BtnMulti;
    private javax.swing.JButton BtnSingle;
    private javax.swing.JButton BtnenviarPalavra;
    private javax.swing.JButton C;
    private javax.swing.JTextField C1;
    private javax.swing.JTextField C10;
    private javax.swing.JTextField C2;
    private javax.swing.JTextField C3;
    private javax.swing.JTextField C4;
    private javax.swing.JTextField C5;
    private javax.swing.JTextField C6;
    private javax.swing.JTextField C7;
    private javax.swing.JTextField C8;
    private javax.swing.JTextField C9;
    private javax.swing.JTextArea CTDica;
    private javax.swing.JTextField CTId;
    private javax.swing.JTextField CTLocalhost;
    private javax.swing.JTextField CTPorta;
    private javax.swing.JButton D;
    private javax.swing.JButton E;
    private javax.swing.JButton F;
    private javax.swing.JButton G;
    private javax.swing.JButton H;
    private javax.swing.JButton I;
    private javax.swing.JButton J;
    private javax.swing.JTextField Jpalavra;
    private javax.swing.JButton K;
    private javax.swing.JButton L;
    private javax.swing.JLabel LabelPlayerI;
    private javax.swing.JLabel LabelPlayerII;
    private javax.swing.JButton M;
    private javax.swing.JButton N;
    private javax.swing.JButton O;
    private javax.swing.JButton P;
    private javax.swing.JTextField PONTOSPLAYI;
    private javax.swing.JTextField PONTOSPLAYII;
    private javax.swing.JPanel PainelDesenho;
    private javax.swing.JPanel PanelJogo;
    private javax.swing.JPanel PanelJogoEscolha;
    private javax.swing.JPanel PanelLog;
    private javax.swing.JPanel Panelconexao;
    private javax.swing.JButton Q;
    private javax.swing.JButton R;
    private javax.swing.JButton S;
    private javax.swing.JButton T;
    private javax.swing.JButton U;
    private javax.swing.JButton V;
    private javax.swing.JButton W;
    private javax.swing.JButton X;
    private javax.swing.JButton Y;
    private javax.swing.JButton Z;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
    private TCPClient tcpClient;

    private void VerificaSeExisteLetra(String letra) {
        tentativa = tentativa + 1;
        Boolean v = false;
        if (C1.getText().toUpperCase().equals(letra.toUpperCase())) {
            C1.setForeground(Color.BLACK);
            v = true;
        }
        if (C2.getText().toUpperCase().equals(letra.toUpperCase())) {
            C2.setForeground(Color.BLACK);
            v = true;
        }
        if (C3.getText().toUpperCase().equals(letra.toUpperCase())) {
            C3.setForeground(Color.BLACK);
            v = true;
        }
        if (C4.getText().toUpperCase().equals(letra.toUpperCase())) {
            C4.setForeground(Color.BLACK);
            v = true;
        }
        if (C5.getText().toUpperCase().equals(letra.toUpperCase())) {
            C5.setForeground(Color.BLACK);
            v = true;
        }
        if (C6.getText().toUpperCase().equals(letra.toUpperCase())) {
            C6.setForeground(Color.BLACK);
            v = true;
        }
        if (C7.getText().toUpperCase().equals(letra.toUpperCase())) {
            C7.setForeground(Color.BLACK);
            v = true;
        }
        if (C8.getText().toUpperCase().equals(letra.toUpperCase())) {
            C8.setForeground(Color.BLACK);
            v = true;
        }
        if (C9.getText().toUpperCase().equals(letra.toUpperCase())) {
            C9.setForeground(Color.BLACK);
            v = true;
        }
        if (C10.getText().toUpperCase().equals(letra.toUpperCase())) {
            C10.setForeground(Color.BLACK);
            v = true;
        }

        if (!v) {
            qtdeerro = qtdeerro + 1;
            Desenho des = new Desenho();
            if (qtdeerro == 1) {
                //des.cabeca(PainelDesenho.getGraphics());
                this.DesenhouCabeca = true;
            }
            if (qtdeerro == 2) {
                //des.corpo(PainelDesenho.getGraphics());
                this.Desenhoucorpo = true;
            }
            if (qtdeerro == 3) {
                //des.bracoDir(PainelDesenho.getGraphics());
                this.DesenhouBracodir = true;
            }
            if (qtdeerro == 4) {
                //des.bracoEsq(PainelDesenho.getGraphics());
                this.DesenhouBracoesq = true;
            }
            if (qtdeerro == 5) {
                //des.pernaDir(PainelDesenho.getGraphics());
                this.DesenhouPernadir = true;
            }
            if (qtdeerro == 6) {
                //des.pernaEsq(PainelDesenho.getGraphics());
                this.DesenhouPernaesq = true;
            }


        }
        DesenharnoPainel();




        if (((C1.getForeground() == Color.BLACK) || (C1.getText().isEmpty()))
                && ((C2.getForeground() == Color.BLACK) || (C2.getText().isEmpty()))
                && ((C3.getForeground() == Color.BLACK) || (C3.getText().isEmpty()))
                && ((C4.getForeground() == Color.BLACK) || (C4.getText().isEmpty()))
                && ((C5.getForeground() == Color.BLACK) || (C5.getText().isEmpty()))
                && ((C6.getForeground() == Color.BLACK) || (C6.getText().isEmpty()))
                && ((C7.getForeground() == Color.BLACK) || (C7.getText().isEmpty()))
                && ((C8.getForeground() == Color.BLACK) || (C8.getText().isEmpty()))
                && ((C9.getForeground() == Color.BLACK) || (C9.getText().isEmpty()))
                && ((C10.getForeground() == Color.BLACK) || (C10.getText().isEmpty()))) {

            JOptionPane.showMessageDialog(rootPane, "voce Venceu");
            this.tcpClient.writeMessage(CTId.getText() + "|TERMINOU|1|0");
            CarregaVazioNoCT();
            DesenharnoPainel();
            if (!multiplayer) {
                int answer = JOptionPane.showConfirmDialog(this, "Jogar novamente?", "Qual que vai ser.", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (answer == JOptionPane.YES_OPTION) {
                    this.tcpClient.writeMessage(CTId.getText() + "|tipo|1|GERARPALAVRA");
                    DesenharnoPainel();
                } else if (answer == JOptionPane.NO_OPTION) {
                    try {
                        this.tcpClient.closeConnection();
                        BtnConectar.setEnabled(true);
                        BtnDesconecta.setEnabled(false);
                        jButton3.setEnabled(false);
                        BtnMulti.setEnabled(false);
                        BtnSingle.setEnabled(false);
                        //PanelJogoEscolha.setVisible(false);
                        BtnCriarnovo.setEnabled(false);
                        BtnEntrar.setEnabled(false);
                        jTable1.setEnabled(false);
                        // PanelLog.setVisible(false);
                        CTId.setText("");
                        jTextArea1.setText("");
                        jTextArea2.setText("");
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                }
            }




        } else if (qtdeerro == 6) {
            JOptionPane.showMessageDialog(rootPane, "voce Perdeu");
            this.tcpClient.writeMessage(CTId.getText() + "|TERMINOU|0|0");
            CarregaVazioNoCT();
            DesenharnoPainel();           
            if (!multiplayer) {
                int answer = JOptionPane.showConfirmDialog(this, "Jogar novamente?", "Qual que vai ser.", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (answer == JOptionPane.YES_OPTION) {
                    this.tcpClient.writeMessage(CTId.getText() + "|tipo|1|GERARPALAVRA");
                    DesenharnoPainel();
                } else if (answer == JOptionPane.NO_OPTION) {
                    try {
                        this.tcpClient.closeConnection();
                        BtnConectar.setEnabled(true);
                        BtnDesconecta.setEnabled(false);
                        jButton3.setEnabled(false);
                        BtnMulti.setEnabled(false);
                        BtnSingle.setEnabled(false);
                        //PanelJogoEscolha.setVisible(false);
                        BtnCriarnovo.setEnabled(false);
                        BtnEntrar.setEnabled(false);
                        jTable1.setEnabled(false);
                        // PanelLog.setVisible(false);
                        CTId.setText("");
                        jTextArea1.setText("");
                        jTextArea2.setText("");
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                }
            }

        }

    }

    @Override
    public void repaint(long time, int x, int y, int width, int height) {
        super.repaint(time, x, y, width, height);
        //DesenharnoPainel();


    }

    @Override
    public void paint(Graphics g) {

        super.paint(g);
        DesenharnoPainel();

    }

    public void DesenharnoPainel() {
        Desenho des = new Desenho();
        if (this.Desenhoucorpo) {
            des.corpo(PainelDesenho.getGraphics());
        }
        if (this.DesenhouPoste) {
            des.poste(PainelDesenho.getGraphics());
        }
        if (this.DesenhouCabeca) {
            des.cabeca(PainelDesenho.getGraphics());
        }
        if (this.DesenhouBracodir) {
            des.bracoDir(PainelDesenho.getGraphics());
        }
        if (this.DesenhouBracoesq) {
            des.bracoEsq(PainelDesenho.getGraphics());
        }
        if (this.DesenhouPernadir) {
            des.pernaDir(PainelDesenho.getGraphics());
        }
        if (this.DesenhouPernaesq) {
            des.pernaEsq(PainelDesenho.getGraphics());
        }
        System.out.println("Funtion Desenhar");


    }

    @Override
    public synchronized void addWindowListener(WindowListener l) {
        super.addWindowListener(l);
    }

    @Override
    public void remove(Component comp) {
        try {
            tcpClient.closeConnection();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        super.remove(comp);
    }
}
